import { useEffect, useMemo, useState } from 'react';
import { AlertTriangle, ArrowLeft, LoaderCircle, Network } from 'lucide-react';
import { getRunProvenanceGraph, listResearchRuns } from '../../api/services';
import { navigate } from '../../routing';
import type { ProvenanceGraphDTO, ResearchRunSummaryDTO } from '../../types';

function Failure({ message }: { message: string }) { return <div className="inline-error" role="alert"><AlertTriangle size={15} />{message}</div>; }
function Loading() { return <p className="muted-copy loading-message" role="status"><LoaderCircle className="spin" size={14} /> Loading provenance graph...</p>; }

export function KnowledgeGraphPage({ runId }: { runId?: string }) {
  const [runs, setRuns] = useState<ResearchRunSummaryDTO[]>([]);
  const [graph, setGraph] = useState<ProvenanceGraphDTO | null>(null);
  const [selected, setSelected] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  useEffect(() => { let active = true; void listResearchRuns().then((value) => { if (active) setRuns(value); }).catch((reason: unknown) => { if (active) setError(reason instanceof Error ? reason.message : 'Research runs could not be loaded.'); }); return () => { active = false; }; }, []);
  useEffect(() => { if (!runId) { setLoading(false); return; } let active = true; setLoading(true); setError(''); void getRunProvenanceGraph(runId).then((value) => { if (active) setGraph(value); }).catch((reason: unknown) => { if (active) setError(reason instanceof Error ? reason.message : 'Provenance graph could not be loaded.'); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [runId]);
  const selectedNode = useMemo(() => graph?.nodes.find((node) => node.node_id === selected) ?? null, [graph, selected]);
  if (!runId) return <section className="secondary-page"><div className="eyebrow">Knowledge / Provenance</div><h1>Knowledge graph</h1><p className="page-lede">Choose an owned research run to inspect only the relationships returned by the provenance service.</p>{error && <Failure message={error} />}{runs.length === 0 && !error && <div className="empty-card"><Network size={18} />No research runs are available for graph inspection.</div>}<div className="record-list">{runs.map((run) => <button className="record-card" type="button" key={run.run_id} onClick={() => navigate(`/knowledge-graph/${encodeURIComponent(run.run_id)}`)}><Network size={17} /><span className="record-main"><strong>{run.query}</strong><small>{run.status}  /  {run.run_id}</small></span><span className="muted-copy">Open graph</span></button>)}</div></section>;
   return <section className="secondary-page graph-page"><div className="eyebrow">Knowledge / Provenance graph</div><button className="text-button" type="button" onClick={() => navigate('/knowledge-graph')}><ArrowLeft size={13} /> Back to runs</button><h1>Research relationships</h1>{loading && <Loading />}{error && <Failure message={error} />}{!loading && !error && graph && <><div className="graph-summary" role="status"><span>{graph.nodes.length} nodes</span><span>{graph.edges.length} relationships</span><span>Backend-authoritative graph</span></div>{graph.nodes.length === 0 ? <div className="empty-card"><Network size={18} />No provenance nodes were returned for this run.</div> : <div className="graph-layout"><section className="graph-nodes" aria-label="Provenance nodes">{graph.nodes.map((node) => <button type="button" className={`graph-node node-${node.node_type.toLowerCase()} ${selected === node.node_id ? 'selected' : ''}`} aria-pressed={selected === node.node_id} key={node.node_id} onClick={() => setSelected(node.node_id)}><span className="eyebrow">{node.node_type}</span><strong>{node.label}</strong><small>{node.entity_id}</small></button>)}</section><section className="graph-edges" aria-label="Provenance relationships"><div className="panel-heading"><span className="eyebrow">Relationships</span><span className="muted-copy">{graph.edges.length} returned</span></div><ul className="relationship-list">{graph.edges.map((edge) => <li key={edge.edge_id}><strong>{edge.relationship_type}</strong><span>{edge.from_node_id.slice(0, 8)}... / {edge.to_node_id.slice(0, 8)}...</span></li>)}</ul></section>{selectedNode && <aside className="graph-inspector" aria-label="Selected node metadata"><div className="eyebrow">Selected node</div><h2>{selectedNode.label}</h2><p>{selectedNode.node_type}  /  {selectedNode.entity_id}</p>{Object.keys(selectedNode.metadata).length === 0 ? <small className="muted-copy">No additional metadata returned.</small> : Object.entries(selectedNode.metadata).map(([key, value]) => <div className="metadata-row" key={key}><span className="eyebrow">{key}</span><span>{typeof value === 'string' ? value : JSON.stringify(value)}</span></div>)}</aside>}</div>}</>}</section>;
}

