import { useEffect, useState } from 'react';
import { AlertTriangle, ArrowRight, CircleDot, FileSearch, LoaderCircle, Network, ShieldAlert } from 'lucide-react';
import { getResearchQuestion, getResearchRun, getRunAnalysis, getRunClaims, getRunProvenance, listResearchQuestions, listResearchRuns } from '../../api/services';
import { navigate } from '../../routing';
import type { ClaimEvidenceDTO, EvidenceTraceDTO, ResearchQuestionDetailDTO, ResearchQuestionSummaryDTO, ResearchResultDTO, ResearchRunDetailDTO, ResearchRunSummaryDTO, SpecialistAnalysisDTO } from '../../types';

function Loading({ label }: { label: string }) { return <p className="muted-copy loading-message" role="status"><LoaderCircle className="spin" size={14} /> {label}</p>; }
function Failure({ message }: { message: string }) { return <div className="inline-error" role="alert"><AlertTriangle size={15} />{message}</div>; }
function formatDate(value?: string | null): string { return value ? new Date(value).toLocaleString() : 'Not reported'; }
function statusClass(status: string): string { return status.toLowerCase().replace(/\s+/g, '-'); }

export function ResearchHistoryPage() {
  const [runs, setRuns] = useState<ResearchRunSummaryDTO[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const load = () => { setLoading(true); setError(''); void listResearchRuns().then(setRuns).catch((reason: unknown) => setError(reason instanceof Error ? reason.message : 'Research history could not be loaded.')).finally(() => setLoading(false)); };
  useEffect(load, []);
  return <section className="secondary-page"><div className="eyebrow">Research / Runs</div><h1>Research history</h1><p className="page-lede">Persisted investigations returned by the backend for this authenticated session.</p><div className="page-actions"><button className="button" type="button" onClick={load}>Refresh</button><button className="button button-primary" type="button" onClick={() => navigate('/research/new')}>New investigation</button></div>{loading && <Loading label="Loading research history..." />}{error && <Failure message={error} />}{!loading && !error && runs.length === 0 && <div className="empty-card"><CircleDot size={18} />No completed or active runs are currently associated with this session.</div>}<div className="record-list">{runs.map((run) => <button className="record-card" type="button" key={run.run_id} onClick={() => navigate(`/research/runs/${encodeURIComponent(run.run_id)}`)}><span className="record-icon"><FileSearch size={17} /></span><span className="record-main"><strong>{run.query}</strong><small>{run.domain || 'Domain not reported'} · Started {formatDate(run.started_at)}</small></span><span className={`status-chip ${statusClass(run.status)}`}>{run.status}</span><ArrowRight size={15} /></button>)}</div></section>;
}

export function ResearchQuestionsPage() {
  const [questions, setQuestions] = useState<ResearchQuestionSummaryDTO[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  useEffect(() => { void listResearchQuestions().then(setQuestions).catch((reason: unknown) => setError(reason instanceof Error ? reason.message : 'Research questions could not be loaded.')).finally(() => setLoading(false)); }, []);
  return <section className="secondary-page"><div className="eyebrow">Research / Questions</div><h1>Research questions</h1><p className="page-lede">Questions are persisted independently from their runs, so continuity remains visible.</p>{loading && <Loading label="Loading questions..." />}{error && <Failure message={error} />}{!loading && !error && questions.length === 0 && <div className="empty-card"><CircleDot size={18} />No persisted research questions are currently available.</div>}<div className="record-list">{questions.map((question) => <button className="record-card" type="button" key={question.question_id} onClick={() => navigate(question.run_ids[0] ? `/research/runs/${encodeURIComponent(question.run_ids[0])}` : '/research')}><span className="record-icon"><Network size={17} /></span><span className="record-main"><strong>{question.main_question}</strong><small>{question.domain || 'Domain not reported'} · {question.run_ids.length} run{question.run_ids.length === 1 ? '' : 's'} · {formatDate(question.created_at)}</small></span><span className={`status-chip ${statusClass(question.research_status)}`}>{question.research_status}</span><ArrowRight size={15} /></button>)}</div></section>;
}

function ObjectFields({ value }: { value: Record<string, unknown> }) { return <div className="object-fields">{Object.entries(value).filter(([key]) => !/(reasoning|chain.of.thought|internal)/i.test(key)).map(([key, field]) => <div key={key}><span className="eyebrow">{key.replace(/_/g, ' ')}</span><p>{typeof field === 'string' ? field : JSON.stringify(field)}</p></div>)}</div>; }

function ClaimsPanel({ claims }: { claims: ClaimEvidenceDTO[] }) { return <section className="record-section"><div className="panel-heading"><span className="eyebrow">Claims / Evidence relationships</span><span className="muted-copy">{claims.length} returned</span></div>{claims.length === 0 ? <p className="muted-copy section-pad">No claim records were returned for this run.</p> : <div className="claim-list">{claims.map((claim) => <article className="claim-card" key={claim.claim_id}><div className="claim-heading"><span className="eyebrow">Claim · {claim.claim_type}</span><span className="status-chip">{claim.lifecycle_status}</span></div><p>{claim.statement}</p><small>{Math.round(claim.confidence * 100)}% confidence · {claim.evidence_links.length} evidence relationship{claim.evidence_links.length === 1 ? '' : 's'}</small>{claim.evidence_links.length > 0 && <ul className="relationship-list">{claim.evidence_links.map((link) => <li key={link.evidence_link_id}><strong>{link.relation_type}</strong><span>Passage {link.passage_id.slice(0, 10)}…</span><em>{link.confidence_weight.toFixed(2)} weight</em></li>)}</ul>}</article>)}</div>}</section>; }

function AnalysisPanel({ analysis }: { analysis: SpecialistAnalysisDTO }) { const groups = Object.entries(analysis) as [string, Record<string, unknown>[]][]; return <section className="record-section"><div className="panel-heading"><span className="eyebrow">Specialist analysis</span><span className="muted-copy">Structured fields only</span></div>{groups.every(([, items]) => items.length === 0) ? <p className="muted-copy section-pad">No specialist analysis was returned for this run.</p> : <div className="analysis-grid">{groups.filter(([, items]) => items.length > 0).map(([name, items]) => <div className="analysis-group" key={name}><span className="eyebrow">{name.replace(/_/g, ' ')}</span>{items.map((item, index) => <article key={`${name}-${index}`}><ObjectFields value={item} /></article>)}</div>)}</div>}</section>; }

function ProvenancePanel({ traces }: { traces: EvidenceTraceDTO[] }) { return <section className="record-section"><div className="panel-heading"><span className="eyebrow">Provenance trace</span><span className="muted-copy">Source → document → passage → claim</span></div>{traces.length === 0 ? <p className="muted-copy section-pad">No provenance trace was returned for this run.</p> : <div className="trace-list">{traces.map((trace) => <details key={trace.evidence_link_id} className="trace-card"><summary><strong>{trace.source.title}</strong><span>{trace.relation_type} · {trace.passage.page_number ? `Page ${trace.passage.page_number}` : 'Page not reported'}</span></summary><div className="trace-body"><p>{trace.passage.content}</p><small>Document {trace.document.document_id} · {trace.document.original_filename || trace.document.mime_type} · Claim {trace.claim_id || 'not linked'}</small>{trace.passage.extraction_uncertainty && <small className="uncertainty-note">Extraction uncertainty reported by backend.</small>}</div></details>)}</div>}</section>; }

function ResultPanel({ result }: { result: ResearchResultDTO | null | undefined }) { if (!result) return <section className="record-section"><div className="section-pad"><ShieldAlert size={16} /> This run has no persisted result yet.</div></section>; return <section className="record-section"><div className="panel-heading"><span className="eyebrow">Final synthesis</span><span className="status-chip">{result.validation_status}</span></div><article className="record-synthesis"><p>{result.final_response}</p><small>{result.validated_claims_count} validated claim{result.validated_claims_count === 1 ? '' : 's'} · {result.retrieved_passages.length} retrieved passage{result.retrieved_passages.length === 1 ? '' : 's'}</small></article></section>; }

export function ResearchRunDetailPage({ runId }: { runId: string }) {
  const [run, setRun] = useState<ResearchRunDetailDTO | null>(null);
  const [claims, setClaims] = useState<ClaimEvidenceDTO[]>([]);
  const [analysis, setAnalysis] = useState<SpecialistAnalysisDTO | null>(null);
  const [provenance, setProvenance] = useState<EvidenceTraceDTO[]>([]);
  const [question, setQuestion] = useState<ResearchQuestionDetailDTO | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  useEffect(() => { let active = true; void Promise.all([getResearchRun(runId), getRunClaims(runId), getRunAnalysis(runId), getRunProvenance(runId)]).then(([runValue, claimValue, analysisValue, provenanceValue]) => { if (!active) return; setRun(runValue); setClaims(claimValue); setAnalysis(analysisValue); setProvenance(provenanceValue); if (runValue.research_question_id) void getResearchQuestion(runValue.research_question_id).then(setQuestion).catch(() => undefined); }).catch((reason: unknown) => { if (active) setError(reason instanceof Error ? reason.message : 'Research record could not be loaded.'); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [runId]);
  if (loading) return <section className="secondary-page"><Loading label="Loading research record..." /></section>;
  if (error || !run) return <section className="secondary-page"><Failure message={error || 'Research record not found.'} /><button className="button" type="button" onClick={() => navigate('/research/runs')}>Back to history</button></section>;
  return <section className="secondary-page record-detail"><div className="eyebrow">Research / Record</div><button className="text-button" type="button" onClick={() => navigate('/research/runs')}>← Back to history</button><h1>{run.query}</h1><div className="record-meta-grid"><span><b>Status</b>{run.status}</span><span><b>Started</b>{formatDate(run.started_at)}</span><span><b>Finished</b>{formatDate(run.finished_at)}</span><span><b>Run ID</b>{run.run_id}</span></div>{question && <section className="question-context panel"><div className="eyebrow">Question context</div><p>{question.main_question}</p>{question.open_questions.length > 0 && <small>Open questions: {question.open_questions.join(' · ')}</small>}</section>}<ResultPanel result={run.result} />{run.error_message && <Failure message={run.error_message} />}{analysis && <AnalysisPanel analysis={analysis} />}<ClaimsPanel claims={claims} /><ProvenancePanel traces={provenance} /><section className="record-section"><div className="panel-heading"><span className="eyebrow">Research activity</span><span className="muted-copy">{run.steps.length} persisted steps</span></div>{run.steps.length === 0 ? <p className="muted-copy section-pad">No persisted activity steps were returned.</p> : <ol className="step-list">{run.steps.map((step) => <li key={step.event_id || `${step.step_name}-${step.created_at}`}><strong>{step.step_name}</strong><span>{step.status} · {formatDate(step.created_at)}</span></li>)}</ol>}</section></section>;
}
