from enum import Enum


class SourceType(str, Enum):
    PRIMARY = "PRIMARY"
    SECONDARY = "SECONDARY"
    TRANSLATION = "TRANSLATION"
    COMMENTARY = "COMMENTARY"
    DISCOVERY_ONLY = "DISCOVERY_ONLY"
    UNVERIFIED = "UNVERIFIED"
    # Compatibility names used by older callers; they map to the existing
    # secondary-source database value and require no new PostgreSQL enum value.
    SCHOLARLY_SECONDARY = "SECONDARY"
    SCIENTIFIC_STUDY = "SECONDARY"

class SourceRelationshipType(str, Enum):
    TRANSLATION_OF = "TRANSLATION_OF"
    COMMENTARY_ON = "COMMENTARY_ON"
    INTERPRETATION_OF = "INTERPRETATION_OF"
    EDITION_OF = "EDITION_OF"

class ClaimType(str, Enum):
    DIRECT_SOURCE_CLAIM = "DIRECT_SOURCE_CLAIM"
    TRANSLATION = "TRANSLATION"
    SCHOLARLY_INTERPRETATION = "SCHOLARLY_INTERPRETATION"
    SCIENTIFIC_FINDING = "SCIENTIFIC_FINDING"
    MODEL_SYNTHESIS = "MODEL_SYNTHESIS"
    INFERENCE = "INFERENCE"
    ANALOGY = "ANALOGY"
    HYPOTHESIS = "HYPOTHESIS"
    SPECULATION = "SPECULATION"
    UNCERTAIN = "UNCERTAIN"

class PramanaType(str, Enum):
    PRATYAKSHA = "pratyaksha"  # Perception
    ANUMANA = "anumana"        # Inference
    UPAMANA = "upamana"        # Comparison
    SHABDA = "shabda"          # Testimony
    ARTHAPATTI = "arthapatti"  # Postulation
    ANUPALABDHI = "anupalabdhi"# Non-apprehension

class RelationType(str, Enum):
    SUPPORTS = "SUPPORTS"
    CONTRADICTS = "CONTRADICTS"
    QUALIFIES = "QUALIFIES"

class EvidenceStatus(str, Enum):
    SUPPORTED = "supported"
    PLAUSIBLE = "plausible"
    CONTESTED = "contested"
    WEAKLY_SUPPORTED = "weakly_supported"
    UNRESOLVED = "unresolved"
    INSUFFICIENT_EVIDENCE = "insufficient_evidence"


class EpistemicState(str, Enum):
    """A calibrated epistemic category, intentionally separate from confidence."""

    ESTABLISHED = "ESTABLISHED"
    WELL_SUPPORTED = "WELL_SUPPORTED"
    PLAUSIBLE = "PLAUSIBLE"
    CONTESTED = "CONTESTED"
    INTERPRETIVE = "INTERPRETIVE"
    INFERENTIAL = "INFERENTIAL"
    SPECULATIVE = "SPECULATIVE"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"
    UNRESOLVED = "UNRESOLVED"
    REJECTED = "REJECTED"


class ReasoningNodeType(str, Enum):
    QUESTION = "QUESTION"
    PROBLEM = "PROBLEM"
    INTERPRETATION = "INTERPRETATION"
    CONCEPT = "CONCEPT"
    TRADITION = "TRADITION"
    SOURCE = "SOURCE"
    PASSAGE = "PASSAGE"
    POSITION = "POSITION"
    ARGUMENT = "ARGUMENT"
    PREMISE = "PREMISE"
    CLAIM = "CLAIM"
    EVIDENCE = "EVIDENCE"
    INFERENCE = "INFERENCE"
    SYNTHESIS = "SYNTHESIS"
    INSIGHT = "INSIGHT"
    COUNTERARGUMENT = "COUNTERARGUMENT"
    RESEARCH_DIRECTION = "RESEARCH_DIRECTION"


class ReasoningRelationType(str, Enum):
    ASKS = "ASKS"
    REFINES = "REFINES"
    CONTAINS = "CONTAINS"
    INVOLVES = "INVOLVES"
    BELONGS_TO = "BELONGS_TO"
    DEFINED_BY = "DEFINED_BY"
    APPEARS_IN = "APPEARS_IN"
    SUPPORTS = "SUPPORTS"
    CONTRADICTS = "CONTRADICTS"
    QUALIFIES = "QUALIFIES"
    COMPLEMENTS = "COMPLEMENTS"
    REINTERPRETS = "REINTERPRETS"
    CRITIQUES = "CRITIQUES"
    PRESUPPOSES = "PRESUPPOSES"
    DERIVES_FROM = "DERIVES_FROM"
    INFERRED_FROM = "INFERRED_FROM"
    SYNTHESIZES = "SYNTHESIZES"
    CHALLENGES = "CHALLENGES"
    ALTERNATIVE_TO = "ALTERNATIVE_TO"
    LEAVES_UNRESOLVED = "LEAVES_UNRESOLVED"


class EmbeddingIndexStatus(str, Enum):
    PENDING = "PENDING"
    INDEXING = "INDEXING"
    INDEXED = "INDEXED"
    FAILED = "FAILED"


class ProvenanceNodeType(str, Enum):
    SOURCE = "SOURCE"
    DOCUMENT = "DOCUMENT"
    DOCUMENT_VERSION = "DOCUMENT_VERSION"
    PAGE = "PAGE"
    PASSAGE = "PASSAGE"
    CLAIM = "CLAIM"
    EVIDENCE = "EVIDENCE"
    SPECIALIST_ANALYSIS = "SPECIALIST_ANALYSIS"
    VALIDATION = "VALIDATION"
    RESEARCH_RUN = "RESEARCH_RUN"
    SYNTHESIS = "SYNTHESIS"


class ProvenanceRelationType(str, Enum):
    CONTAINS = "CONTAINS"
    HAS_VERSION = "HAS_VERSION"
    SUPPORTS = "SUPPORTS"
    CONTRADICTS = "CONTRADICTS"
    QUALIFIES = "QUALIFIES"
    CITES = "CITES"
    DERIVES_FROM = "DERIVES_FROM"
    VALIDATED_BY = "VALIDATED_BY"
    CONTRIBUTES_TO = "CONTRIBUTES_TO"
    PRODUCES = "PRODUCES"
    HAS_ANALYSIS = "HAS_ANALYSIS"
    HAS_VALIDATION = "HAS_VALIDATION"
    HAS_EVIDENCE = "HAS_EVIDENCE"
    VALIDATES = "VALIDATES"
