from enum import Enum

class SourceType(str, Enum):
    PRIMARY = "PRIMARY"
    TRANSLATION = "TRANSLATION"
    TRADITIONAL_COMMENTARY = "TRADITIONAL_COMMENTARY"
    SCHOLARLY_SECONDARY = "SCHOLARLY_SECONDARY"
    SCIENTIFIC_STUDY = "SCIENTIFIC_STUDY"
    REVIEW_OR_META_ANALYSIS = "REVIEW_OR_META_ANALYSIS"
    INSTITUTIONAL = "INSTITUTIONAL"
    GENERAL_REFERENCE = "GENERAL_REFERENCE"
    DISCOVERY_ONLY = "DISCOVERY_ONLY"
    UNVERIFIED = "UNVERIFIED"

class SourceRelationshipType(str, Enum):
    TRANSLATION_OF = "TRANSLATION_OF"
    COMMENTARY_ON = "COMMENTARY_ON"
    EDITION_OF = "EDITION_OF"
    INTERPRETATION_OF = "INTERPRETATION_OF"
    SYNTHESIS_OF = "SYNTHESIS_OF"

class ClaimType(str, Enum):
    DIRECT_SOURCE_CLAIM = "DIRECT_SOURCE_CLAIM"
    TRANSLATION = "TRANSLATION"
    SCHOLARLY_INTERPRETATION = "SCHOLARLY_INTERPRETATION"
    SCIENTIFIC_FINDING = "SCIENTIFIC_FINDING"
    MODEL_SYNTHESIS = "MODEL_SYNTHESIS"
    INFERENCE = "INFERENCE"
    ANALOGY = "ANALOGY"
    HYPOTHESIS = "HYPOTHESIS"
    SPECULATION = "SPECULATION"
    UNCERTAIN = "UNCERTAIN"

class EvidenceStatus(str, Enum):
    SUPPORTED = "supported"
    PLAUSIBLE = "plausible"
    CONTESTED = "contested"
    WEAKLY_SUPPORTED = "weakly_supported"
    UNRESOLVED = "unresolved"
    INSUFFICIENT_EVIDENCE = "insufficient_evidence"

class RelationType(str, Enum):
    SUPPORTS = "supports"
    CONTRADICTS = "contradicts"
    QUALIFIES = "qualifies"
    INDEPENDENT = "independent"

class PramanaType(str, Enum):
    PRATYAKSHA = "pratyaksha"  
    ANUMANA = "anumana"        
    UPAMANA = "upamana"        
    SHABDA = "shabda"          
    ARTHAPATTI = "arthapatti"  
    ANUPALABDHI = "anupalabdhi"